using System.ComponentModel;

namespace CarParkAutomatisation
{
    partial class OtoparkYerlesimi
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.b2Btn = new MetroFramework.Controls.MetroButton();
            this.b1Btn = new MetroFramework.Controls.MetroButton();
            this.a2Btn = new MetroFramework.Controls.MetroButton();
            this.a1Btn = new MetroFramework.Controls.MetroButton();
            this.a3Btn = new MetroFramework.Controls.MetroButton();
            this.a4Btn = new MetroFramework.Controls.MetroButton();
            this.b3Btn = new MetroFramework.Controls.MetroButton();
            this.b4Btn = new MetroFramework.Controls.MetroButton();
            this.a5Btn = new MetroFramework.Controls.MetroButton();
            this.a6Btn = new MetroFramework.Controls.MetroButton();
            this.b5Btn = new MetroFramework.Controls.MetroButton();
            this.b6Btn = new MetroFramework.Controls.MetroButton();
            this.c5Btn = new MetroFramework.Controls.MetroButton();
            this.c6Btn = new MetroFramework.Controls.MetroButton();
            this.d5Btn = new MetroFramework.Controls.MetroButton();
            this.d6Btn = new MetroFramework.Controls.MetroButton();
            this.c3Btn = new MetroFramework.Controls.MetroButton();
            this.c4Btn = new MetroFramework.Controls.MetroButton();
            this.d3Btn = new MetroFramework.Controls.MetroButton();
            this.d4Btn = new MetroFramework.Controls.MetroButton();
            this.c1Btn = new MetroFramework.Controls.MetroButton();
            this.c2Btn = new MetroFramework.Controls.MetroButton();
            this.d1Btn = new MetroFramework.Controls.MetroButton();
            this.d2Btn = new MetroFramework.Controls.MetroButton();
            this.e5Btn = new MetroFramework.Controls.MetroButton();
            this.e6Btn = new MetroFramework.Controls.MetroButton();
            this.f5Btn = new MetroFramework.Controls.MetroButton();
            this.f6Btn = new MetroFramework.Controls.MetroButton();
            this.e3Btn = new MetroFramework.Controls.MetroButton();
            this.e4Btn = new MetroFramework.Controls.MetroButton();
            this.f3Btn = new MetroFramework.Controls.MetroButton();
            this.f4Btn = new MetroFramework.Controls.MetroButton();
            this.e1Btn = new MetroFramework.Controls.MetroButton();
            this.e2Btn = new MetroFramework.Controls.MetroButton();
            this.f1Btn = new MetroFramework.Controls.MetroButton();
            this.f2Btn = new MetroFramework.Controls.MetroButton();
            this.otoparkYerlesimiLbl = new System.Windows.Forms.Label();
            this.otoparktanCikisBtn = new MetroFramework.Controls.MetroButton();
            this.SuspendLayout();
            this.b2Btn.Location = new System.Drawing.Point(224, 144);
            this.b2Btn.Name = "b2Btn";
            this.b2Btn.Size = new System.Drawing.Size(101, 44);
            this.b2Btn.TabIndex = 8;
            this.b2Btn.Text = "B2";
            this.b2Btn.UseSelectable = true;
            this.b2Btn.Click += new System.EventHandler(this.b2Btn_Click);
            this.b1Btn.Location = new System.Drawing.Point(93, 144);
            this.b1Btn.Name = "b1Btn";
            this.b1Btn.Size = new System.Drawing.Size(101, 44);
            this.b1Btn.TabIndex = 7;
            this.b1Btn.Text = "B1";
            this.b1Btn.UseSelectable = true;
            this.b1Btn.Click += new System.EventHandler(this.b1Btn_Click);
            this.a2Btn.Location = new System.Drawing.Point(224, 80);
            this.a2Btn.Name = "a2Btn";
            this.a2Btn.Size = new System.Drawing.Size(101, 44);
            this.a2Btn.TabIndex = 2;
            this.a2Btn.Text = "A2";
            this.a2Btn.UseSelectable = true;
            this.a2Btn.Click += new System.EventHandler(this.a2Btn_Click);
            this.a1Btn.Location = new System.Drawing.Point(93, 80);
            this.a1Btn.Name = "a1Btn";
            this.a1Btn.Size = new System.Drawing.Size(101, 44);
            this.a1Btn.TabIndex = 1;
            this.a1Btn.Text = "A1";
            this.a1Btn.UseSelectable = true;
            this.a1Btn.Click += new System.EventHandler(this.a1Btn_Click);
            this.a3Btn.Location = new System.Drawing.Point(357, 80);
            this.a3Btn.Name = "a3Btn";
            this.a3Btn.Size = new System.Drawing.Size(101, 44);
            this.a3Btn.TabIndex = 3;
            this.a3Btn.Text = "A3";
            this.a3Btn.UseSelectable = true;
            this.a3Btn.Click += new System.EventHandler(this.a3Btn_Click);
            this.a4Btn.Location = new System.Drawing.Point(488, 80);
            this.a4Btn.Name = "a4Btn";
            this.a4Btn.Size = new System.Drawing.Size(101, 44);
            this.a4Btn.TabIndex = 4;
            this.a4Btn.Text = "A4";
            this.a4Btn.UseSelectable = true;
            this.a4Btn.Click += new System.EventHandler(this.a4Btn_Click);
            this.b3Btn.Location = new System.Drawing.Point(357, 144);
            this.b3Btn.Name = "b3Btn";
            this.b3Btn.Size = new System.Drawing.Size(101, 44);
            this.b3Btn.TabIndex = 9;
            this.b3Btn.Text = "B3";
            this.b3Btn.UseSelectable = true;
            this.b4Btn.Location = new System.Drawing.Point(488, 144);
            this.b4Btn.Name = "b4Btn";
            this.b4Btn.Size = new System.Drawing.Size(101, 44);
            this.b4Btn.TabIndex = 10;
            this.b4Btn.Text = "B4";
            this.b4Btn.UseSelectable = true;
            this.b4Btn.Click += new System.EventHandler(this.b4Btn_Click);
            this.a5Btn.Location = new System.Drawing.Point(617, 80);
            this.a5Btn.Name = "a5Btn";
            this.a5Btn.Size = new System.Drawing.Size(101, 44);
            this.a5Btn.TabIndex = 5;
            this.a5Btn.Text = "A5";
            this.a5Btn.UseSelectable = true;
            this.a5Btn.Click += new System.EventHandler(this.a5Btn_Click);
            this.a6Btn.Location = new System.Drawing.Point(748, 80);
            this.a6Btn.Name = "a6Btn";
            this.a6Btn.Size = new System.Drawing.Size(101, 44);
            this.a6Btn.TabIndex = 6;
            this.a6Btn.Text = "A6";
            this.a6Btn.UseSelectable = true;
            this.a6Btn.Click += new System.EventHandler(this.a6Btn_Click);
            this.b5Btn.Location = new System.Drawing.Point(617, 144);
            this.b5Btn.Name = "b5Btn";
            this.b5Btn.Size = new System.Drawing.Size(101, 44);
            this.b5Btn.TabIndex = 11;
            this.b5Btn.Text = "B5";
            this.b5Btn.UseSelectable = true;
            this.b6Btn.Location = new System.Drawing.Point(748, 144);
            this.b6Btn.Name = "b6Btn";
            this.b6Btn.Size = new System.Drawing.Size(101, 44);
            this.b6Btn.TabIndex = 12;
            this.b6Btn.Text = "B6";
            this.b6Btn.UseSelectable = true;
            this.b6Btn.Click += new System.EventHandler(this.b6Btn_Click);
            this.c5Btn.Location = new System.Drawing.Point(617, 208);
            this.c5Btn.Name = "c5Btn";
            this.c5Btn.Size = new System.Drawing.Size(101, 44);
            this.c5Btn.TabIndex = 17;
            this.c5Btn.Text = "C5";
            this.c5Btn.UseSelectable = true;
            this.c5Btn.Click += new System.EventHandler(this.c5Btn_Click);
            this.c6Btn.Location = new System.Drawing.Point(748, 208);
            this.c6Btn.Name = "c6Btn";
            this.c6Btn.Size = new System.Drawing.Size(101, 44);
            this.c6Btn.TabIndex = 18;
            this.c6Btn.Text = "C6";
            this.c6Btn.UseSelectable = true;
            this.c6Btn.Click += new System.EventHandler(this.c6Btn_Click);
            this.d5Btn.Location = new System.Drawing.Point(617, 272);
            this.d5Btn.Name = "d5Btn";
            this.d5Btn.Size = new System.Drawing.Size(101, 44);
            this.d5Btn.TabIndex = 23;
            this.d5Btn.Text = "D5";
            this.d5Btn.UseSelectable = true;
            this.d5Btn.Click += new System.EventHandler(this.d5Btn_Click);
            this.d6Btn.Location = new System.Drawing.Point(748, 272);
            this.d6Btn.Name = "d6Btn";
            this.d6Btn.Size = new System.Drawing.Size(101, 44);
            this.d6Btn.TabIndex = 24;
            this.d6Btn.Text = "D6";
            this.d6Btn.UseSelectable = true;
            this.d6Btn.Click += new System.EventHandler(this.d6Btn_Click);
            this.c3Btn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.c3Btn.Location = new System.Drawing.Point(357, 208);
            this.c3Btn.Name = "c3Btn";
            this.c3Btn.Size = new System.Drawing.Size(101, 44);
            this.c3Btn.TabIndex = 15;
            this.c3Btn.Text = "C3";
            this.c3Btn.UseSelectable = true;
            this.c3Btn.Click += new System.EventHandler(this.c3Btn_Click);
            this.c4Btn.Location = new System.Drawing.Point(488, 208);
            this.c4Btn.Name = "c4Btn";
            this.c4Btn.Size = new System.Drawing.Size(101, 44);
            this.c4Btn.TabIndex = 16;
            this.c4Btn.Text = "C4";
            this.c4Btn.UseSelectable = true;
            this.c4Btn.Click += new System.EventHandler(this.c4Btn_Click);
            this.d3Btn.Location = new System.Drawing.Point(357, 272);
            this.d3Btn.Name = "d3Btn";
            this.d3Btn.Size = new System.Drawing.Size(101, 44);
            this.d3Btn.TabIndex = 21;
            this.d3Btn.Text = "D3";
            this.d3Btn.UseSelectable = true;
            this.d3Btn.Click += new System.EventHandler(this.d3Btn_Click);
            this.d4Btn.Location = new System.Drawing.Point(488, 272);
            this.d4Btn.Name = "d4Btn";
            this.d4Btn.Size = new System.Drawing.Size(101, 44);
            this.d4Btn.TabIndex = 22;
            this.d4Btn.Text = "D4";
            this.d4Btn.UseSelectable = true;
            this.d4Btn.Click += new System.EventHandler(this.d4Btn_Click);
            this.c1Btn.Location = new System.Drawing.Point(93, 208);
            this.c1Btn.Name = "c1Btn";
            this.c1Btn.Size = new System.Drawing.Size(101, 44);
            this.c1Btn.TabIndex = 13;
            this.c1Btn.Text = "C1";
            this.c1Btn.UseSelectable = true;
            this.c1Btn.Click += new System.EventHandler(this.c1Btn_Click);
            this.c2Btn.Location = new System.Drawing.Point(224, 208);
            this.c2Btn.Name = "c2Btn";
            this.c2Btn.Size = new System.Drawing.Size(101, 44);
            this.c2Btn.TabIndex = 14;
            this.c2Btn.Text = "C2";
            this.c2Btn.UseSelectable = true;
            this.c2Btn.Click += new System.EventHandler(this.c2Btn_Click);
            this.d1Btn.Location = new System.Drawing.Point(93, 272);
            this.d1Btn.Name = "d1Btn";
            this.d1Btn.Size = new System.Drawing.Size(101, 44);
            this.d1Btn.TabIndex = 19;
            this.d1Btn.Text = "D1";
            this.d1Btn.UseSelectable = true;
            this.d1Btn.Click += new System.EventHandler(this.d1Btn_Click);
            this.d2Btn.Location = new System.Drawing.Point(224, 272);
            this.d2Btn.Name = "d2Btn";
            this.d2Btn.Size = new System.Drawing.Size(101, 44);
            this.d2Btn.TabIndex = 20;
            this.d2Btn.Text = "D2";
            this.d2Btn.UseSelectable = true;
            this.d2Btn.Click += new System.EventHandler(this.d2Btn_Click);
            this.e5Btn.Location = new System.Drawing.Point(617, 333);
            this.e5Btn.Name = "e5Btn";
            this.e5Btn.Size = new System.Drawing.Size(101, 44);
            this.e5Btn.TabIndex = 29;
            this.e5Btn.Text = "E5";
            this.e5Btn.UseSelectable = true;
            this.e5Btn.Click += new System.EventHandler(this.e5Btn_Click);
            this.e6Btn.Location = new System.Drawing.Point(748, 333);
            this.e6Btn.Name = "e6Btn";
            this.e6Btn.Size = new System.Drawing.Size(101, 44);
            this.e6Btn.TabIndex = 30;
            this.e6Btn.Text = "E6";
            this.e6Btn.UseSelectable = true;
            this.e6Btn.Click += new System.EventHandler(this.e6Btn_Click);
            this.f5Btn.Location = new System.Drawing.Point(617, 397);
            this.f5Btn.Name = "f5Btn";
            this.f5Btn.Size = new System.Drawing.Size(101, 44);
            this.f5Btn.TabIndex = 35;
            this.f5Btn.Text = "F5";
            this.f5Btn.UseSelectable = true;
            this.f5Btn.Click += new System.EventHandler(this.f5Btn_Click);
            this.f6Btn.Location = new System.Drawing.Point(748, 397);
            this.f6Btn.Name = "f6Btn";
            this.f6Btn.Size = new System.Drawing.Size(101, 44);
            this.f6Btn.TabIndex = 36;
            this.f6Btn.Text = "F6";
            this.f6Btn.UseSelectable = true;
            this.e3Btn.Location = new System.Drawing.Point(357, 333);
            this.e3Btn.Name = "e3Btn";
            this.e3Btn.Size = new System.Drawing.Size(101, 44);
            this.e3Btn.TabIndex = 27;
            this.e3Btn.Text = "E3";
            this.e3Btn.UseSelectable = true;
            this.e3Btn.Click += new System.EventHandler(this.e3Btn_Click);
            this.e4Btn.Location = new System.Drawing.Point(488, 333);
            this.e4Btn.Name = "e4Btn";
            this.e4Btn.Size = new System.Drawing.Size(101, 44);
            this.e4Btn.TabIndex = 28;
            this.e4Btn.Text = "E4";
            this.e4Btn.UseSelectable = true;
            this.e4Btn.Click += new System.EventHandler(this.e4Btn_Click);
            this.f3Btn.Location = new System.Drawing.Point(357, 397);
            this.f3Btn.Name = "f3Btn";
            this.f3Btn.Size = new System.Drawing.Size(101, 44);
            this.f3Btn.TabIndex = 33;
            this.f3Btn.Text = "F3";
            this.f3Btn.UseSelectable = true;
            this.f3Btn.Click += new System.EventHandler(this.f3Btn_Click);
            this.f4Btn.Location = new System.Drawing.Point(488, 397);
            this.f4Btn.Name = "f4Btn";
            this.f4Btn.Size = new System.Drawing.Size(101, 44);
            this.f4Btn.TabIndex = 34;
            this.f4Btn.Text = "F4";
            this.f4Btn.UseSelectable = true;
            this.f4Btn.Click += new System.EventHandler(this.f4Btn_Click);
            this.e1Btn.Location = new System.Drawing.Point(93, 333);
            this.e1Btn.Name = "e1Btn";
            this.e1Btn.Size = new System.Drawing.Size(101, 44);
            this.e1Btn.TabIndex = 25;
            this.e1Btn.Text = "E1";
            this.e1Btn.UseSelectable = true;
            this.e1Btn.Click += new System.EventHandler(this.e1Btn_Click);
            this.e2Btn.Location = new System.Drawing.Point(224, 333);
            this.e2Btn.Name = "e2Btn";
            this.e2Btn.Size = new System.Drawing.Size(101, 44);
            this.e2Btn.TabIndex = 26;
            this.e2Btn.Text = "E2";
            this.e2Btn.UseSelectable = true;
            this.e2Btn.Click += new System.EventHandler(this.e2Btn_Click);
            this.f1Btn.Location = new System.Drawing.Point(93, 397);
            this.f1Btn.Name = "f1Btn";
            this.f1Btn.Size = new System.Drawing.Size(101, 44);
            this.f1Btn.TabIndex = 31;
            this.f1Btn.Text = "F1";
            this.f1Btn.UseSelectable = true;
            this.f1Btn.Click += new System.EventHandler(this.f1Btn_Click);
            this.f2Btn.Location = new System.Drawing.Point(224, 397);
            this.f2Btn.Name = "f2Btn";
            this.f2Btn.Size = new System.Drawing.Size(101, 44);
            this.f2Btn.TabIndex = 32;
            this.f2Btn.Text = "F2";
            this.f2Btn.UseSelectable = true;
            this.f2Btn.Click += new System.EventHandler(this.f2Btn_Click);
            this.otoparkYerlesimiLbl.BackColor = System.Drawing.Color.Transparent;
            this.otoparkYerlesimiLbl.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte) (162)));
            this.otoparkYerlesimiLbl.Location = new System.Drawing.Point(194, 33);
            this.otoparkYerlesimiLbl.Name = "otoparkYerlesimiLbl";
            this.otoparkYerlesimiLbl.Size = new System.Drawing.Size(626, 29);
            this.otoparkYerlesimiLbl.TabIndex = 42;
            this.otoparkYerlesimiLbl.Text = "HOŞGELDİNİZ. PARK ETMEK İSTEDİĞİNİZ YERİ SEÇİNİZ.";
            this.otoparktanCikisBtn.Location = new System.Drawing.Point(328, 467);
            this.otoparktanCikisBtn.Name = "otoparktanCikisBtn";
            this.otoparktanCikisBtn.Size = new System.Drawing.Size(279, 56);
            this.otoparktanCikisBtn.TabIndex = 43;
            this.otoparktanCikisBtn.Text = "Otoparktan Çıkış";
            this.otoparktanCikisBtn.UseSelectable = true;
            this.otoparktanCikisBtn.Click += new System.EventHandler(this.otoparktanCikisBtn_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(941, 535);
            this.Controls.Add(this.otoparktanCikisBtn);
            this.Controls.Add(this.otoparkYerlesimiLbl);
            this.Controls.Add(this.e5Btn);
            this.Controls.Add(this.e6Btn);
            this.Controls.Add(this.f5Btn);
            this.Controls.Add(this.f6Btn);
            this.Controls.Add(this.e3Btn);
            this.Controls.Add(this.e4Btn);
            this.Controls.Add(this.f3Btn);
            this.Controls.Add(this.f4Btn);
            this.Controls.Add(this.e1Btn);
            this.Controls.Add(this.e2Btn);
            this.Controls.Add(this.f1Btn);
            this.Controls.Add(this.f2Btn);
            this.Controls.Add(this.c5Btn);
            this.Controls.Add(this.c6Btn);
            this.Controls.Add(this.d5Btn);
            this.Controls.Add(this.d6Btn);
            this.Controls.Add(this.c3Btn);
            this.Controls.Add(this.c4Btn);
            this.Controls.Add(this.d3Btn);
            this.Controls.Add(this.d4Btn);
            this.Controls.Add(this.c1Btn);
            this.Controls.Add(this.c2Btn);
            this.Controls.Add(this.d1Btn);
            this.Controls.Add(this.d2Btn);
            this.Controls.Add(this.a5Btn);
            this.Controls.Add(this.a6Btn);
            this.Controls.Add(this.b5Btn);
            this.Controls.Add(this.b6Btn);
            this.Controls.Add(this.a3Btn);
            this.Controls.Add(this.a4Btn);
            this.Controls.Add(this.b3Btn);
            this.Controls.Add(this.b4Btn);
            this.Controls.Add(this.a1Btn);
            this.Controls.Add(this.a2Btn);
            this.Controls.Add(this.b1Btn);
            this.Controls.Add(this.b2Btn);
            this.Name = "OtoparkYerlesimi";
            this.Text = "OtoparkYerlesimi";
            this.ResumeLayout(false);
        }

        private MetroFramework.Controls.MetroButton a1Btn;
        private MetroFramework.Controls.MetroButton a2Btn;
        private MetroFramework.Controls.MetroButton a3Btn;
        private MetroFramework.Controls.MetroButton a4Btn;
        private MetroFramework.Controls.MetroButton a5Btn;
        private MetroFramework.Controls.MetroButton a6Btn;
        private MetroFramework.Controls.MetroButton b1Btn;
        private MetroFramework.Controls.MetroButton b2Btn;
        private MetroFramework.Controls.MetroButton b3Btn;
        private MetroFramework.Controls.MetroButton b4Btn;
        private MetroFramework.Controls.MetroButton b5Btn;
        private MetroFramework.Controls.MetroButton b6Btn;
        private MetroFramework.Controls.MetroButton c1Btn;
        private MetroFramework.Controls.MetroButton c2Btn;
        private MetroFramework.Controls.MetroButton c3Btn;
        private MetroFramework.Controls.MetroButton c4Btn;
        private MetroFramework.Controls.MetroButton c5Btn;
        private MetroFramework.Controls.MetroButton c6Btn;
        private MetroFramework.Controls.MetroButton d1Btn;
        private MetroFramework.Controls.MetroButton d2Btn;
        private MetroFramework.Controls.MetroButton d3Btn;
        private MetroFramework.Controls.MetroButton d4Btn;
        private MetroFramework.Controls.MetroButton d5Btn;
        private MetroFramework.Controls.MetroButton d6Btn;
        private MetroFramework.Controls.MetroButton e1Btn;
        private MetroFramework.Controls.MetroButton e2Btn;
        private MetroFramework.Controls.MetroButton e3Btn;
        private MetroFramework.Controls.MetroButton e4Btn;
        private MetroFramework.Controls.MetroButton e5Btn;
        private MetroFramework.Controls.MetroButton e6Btn;
        private MetroFramework.Controls.MetroButton f1Btn;
        private MetroFramework.Controls.MetroButton f2Btn;
        private MetroFramework.Controls.MetroButton f3Btn;
        private MetroFramework.Controls.MetroButton f4Btn;
        private MetroFramework.Controls.MetroButton f5Btn;
        private MetroFramework.Controls.MetroButton f6Btn;
        private MetroFramework.Controls.MetroButton otoparktanCikisBtn;
        private System.Windows.Forms.Label otoparkYerlesimiLbl;

        #endregion
    }
}